# Generated by Django 5.2.8 on 2025-12-04 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Bölüm', 'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Doktor', 'verbose_name_plural': 'Doktorlar'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='leave_dates',
            field=models.JSONField(blank=True, default=list, help_text='İzinli olunan tarihler (JSON formatında)', verbose_name='İzin Günleri'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Haftalık çalışma saatleri (JSON formatında)', verbose_name='Çalışma Saatleri'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor', verbose_name='Doktor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Hasta'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Saat'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Yönetici'), (2, 'Sekreter'), (3, 'Doktor'), (4, 'Hasta')], default=4, verbose_name='Kullanıcı Tipi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bölüm Adı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unvan'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
