# Generated by Django 5.2.8 on 2025-12-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='weekend_duty',
            field=models.JSONField(blank=True, default=list, help_text='Hafta sonu çalışma günleri: [5] = Cumartesi, [6] = Pazar, [5, 6] = Her ikisi', verbose_name='Hafta Sonu Nöbeti'),
        ),
    ]
