# Generated by Django 5.2.8 on 2025-12-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_weekend_duty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='weekend_duty',
        ),
    ]
