# Generated by Django 5.2.8 on 2025-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emergencyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_emergency_doctor',
            field=models.BooleanField(default=False, help_text='Bu doktor acil serviste çalışıyorsa işaretleyin', verbose_name='Acil Servis Doktoru'),
        ),
    ]
