# Generated by Django 5.2.8 on 2025-12-04 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doctor_is_emergency_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(verbose_name='İstenen Tarih')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='İzin Nedeni')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İncelenme Tarihi')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notları')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.doctor', verbose_name='Doktor')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
            ],
            options={
                'verbose_name': 'İzin Talebi',
                'verbose_name_plural': 'İzin Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
