# Generated by Django 5.2.8 on 2025-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Randevu Ücreti (TL)'),
        ),
    ]
