# Generated by Django 5.2.8 on 2025-12-05 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Doktorun koyduğu teşhis', null=True, verbose_name='Teşhis'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_complaints',
            field=models.TextField(blank=True, help_text='Hastanın belirttiği şikayetler', null=True, verbose_name='Hasta Şikayetleri'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, help_text='Verilen ilaçlar ve dozajları', null=True, verbose_name='Reçete'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Doktorun önerileri ve tavsiyeleri', null=True, verbose_name='Öneriler'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='core.appointment', verbose_name='Randevu'),
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(blank=True, null=True, verbose_name='Rapor İçeriği')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='medical_reports/', verbose_name='PDF Rapor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_report', to='core.appointment', verbose_name='Randevu')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='core.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Muayene Raporu',
                'verbose_name_plural': 'Muayene Raporları',
                'ordering': ['-created_at'],
            },
        ),
    ]
