# Generated by Django 5.2.8 on 2025-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointment_diagnosis_appointment_patient_complaints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_token',
            field=models.CharField(blank=True, help_text='Email ile iptal için güvenli token', max_length=64, null=True, verbose_name='İptal Token'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='completed', max_length=20, verbose_name='Durum'),
        ),
    ]
