# Generated by Django 5.2.8 on 2025-12-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointment_cancel_token_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('expires_at', models.DateTimeField(verbose_name='Son Geçerlilik Tarihi')),
                ('used', models.BooleanField(default=False, verbose_name='Kullanıldı mı?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Şifre Sıfırlama Token',
                'verbose_name_plural': 'Şifre Sıfırlama Tokenları',
                'ordering': ['-created_at'],
            },
        ),
    ]
